server:
  port: 8080

spring:
  application:
    name: order-service-hexagonal
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # Ensure Hibernate initializes after the datasource
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 1
        buffer.memory: 33554432

logging:
  level:
    org:springframework: INFO
    com.example.order: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
