apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: order-service-hexagonal-ns
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'order-service-hexagonal'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['order-service-hexagonal:8080']
