apiVersion: v1
kind: Namespace
metadata:
  name: order-service-hexagonal-ns
  labels:
    app.kubernetes.io/name: order-service-hexagonal #   The name of the application
    app.kubernetes.io/part-of: order-service # The name of the larger application this one is part of
