apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: order-service-hexagonal-ns
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
      name: beats
    - port: 5000
      targetPort: 5000
      name: tcp
    - port: 9600
      targetPort: 9600
      name: api
