# logstash/pipeline/logstash.conf
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    # Ajouter le champ application SEULEMENT s'il n'existe pas déjà
    if ![application] {
      mutate {
        add_field => { "application" => "order-service-hexagonal" }
      }
    }

    # Ajouter une étiquette "error" si le niveau de log est ERROR
    if [level] == "ERROR" {
      mutate {
        add_tag => ["error"]
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "order-service-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
