apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: order-service-hexagonal-ns
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5437
      targetPort: 5437
      name: postgres
