apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: order-service-hexagonal-ns
  labels:
    app: kafka
data:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9096,CONTROLLER://0.0.0.0:9097"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.order-service-hexagonal-ns.svc.cluster.local:9096"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9097"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
