apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: order-service-hexagonal-ns
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: 9096
      targetPort: 9096
      name: plaintext
    - port: 9097
      targetPort: 9097
      name: controller
